version: "2"

services:
  cameltest:
    build:
      context: ./camel
    volumes:
      - "cameltest:/measurements:rw"
      - "../maven/datalab-example.war:/opt/jboss/wildfly/standalone/deployments/datalab-example.war:rw"
    ports:
      - "9990:9990"
      - "8080:8080"
    environment:
      MEASUREMENT_DELAY: ${DELAY}
      WILDFLY_MANAGEMENT_USER: admin
      WILDFLY_MANAGEMENT_PASSWORD: admin
      JVM_OPTS: "-Xmx6g -Xms6g -XX:MaxPermSize=1024m"
    extra_hosts:
      - "camelreceiver:${SENDER}"
  starter:
    build:
      context: ./starter
    environment:
      INSTALLATION: ${INSTALLATION}
      AMOUNT: ${AMOUNT}
      DELAY: ${DELAY}
      DURATION: ${DURATION}
      SENDER: http://${SENDER}:3000
      ENDPOINT: http://${TESTMASCHINE}:8080/datalab-example/endpoints/pvreceiver

volumes:
  cameltest:
    driver: local
