version: "2"

services:
  receiver:
    build:
      context: receiver
    restart: unless-stopped
    volumes:
      - nodered_receiver:/measurements:rw
#    Only required for debugging
#    ports:
#      - "1881:1880"
  test:
    build:
      context: nodered
    restart: unless-stopped
    volumes:
      - nodered_test:/measurements:rw
    environment:
      MEASUREMENT_DELAY: 60
#    Only required for debugging
#    ports:
#      - "1880:1880"
    depends_on:
      - receiver
  sender:
    build:
      context: sender
    restart: unless-stopped
    volumes:
      - nodered_sender:/measurements:rw
    environment:
      MEASUREMENT_DELAY: 60
      INSTALLATION: test
      AMOUNT: 1
      ENDPOINT: http://test:1880/endpoints/pvreceiver
    depends_on:
      - test

volumes:
  nodered_sender:
    driver: local
  nodered_test:
    driver: local
  nodered_receiver:
    driver: local
