version: "2"

services:
  receiver:
    build:
      context: receiver
    restart: unless-stopped
    volumes:
      - camel_receiver:/measurements:rw
  deploy:
    build:
      context: maven
    depends_on:
      - test
  test:
    build:
      context: camel
    restart: unless-stopped
    volumes:
      - camel_test:/measurements:rw
    ports:
      - "9990:9990"
      - "8080:8080"
    environment:
      MEASUREMENT_DELAY: 60
      WILDFLY_MANAGEMENT_USER: admin
      WILDFLY_MANAGEMENT_PASSWORD: admin
    depends_on:
      - receiver
  sender:
    build:
      context: sender
    restart: unless-stopped
    volumes:
      - camel_sender:/measurements:rw
    environment:
      MEASUREMENT_DELAY: 60
      INSTALLATION: test
      AMOUNT: 1
      ENDPOINT: http://test:8080/datalab-example/endpoints/pvreceiver
    depends_on:
      - test

volumes:
  camel_sender:
    driver: local
  camel_test:
    driver: local
  camel_receiver:
    driver: local
