version: "2"

services:
  camelreceiver:
    build:
      context: receiver
    restart: unless-stopped
#    Only required for debugging
#    ports:
#      - "1881:1880"
    volumes:
      - camelreceiver:/measurements:rw
  cameldeploy:
    build:
      context: maven
    depends_on:
      - cameltest
  cameltest:
    build:
      context: camel
    restart: unless-stopped
    volumes:
      - cameltest:/measurements:rw
    ports:
      - "9990:9990"
      - "8080:8080"
    environment:
      MEASUREMENT_DELAY: 60
      WILDFLY_MANAGEMENT_USER: admin
      WILDFLY_MANAGEMENT_PASSWORD: admin
    depends_on:
      - camelreceiver
  camelsender:
    build:
      context: sender
    restart: unless-stopped
    volumes:
      - camelsender:/measurements:rw
    environment:
      MEASUREMENT_DELAY: 60
      INSTALLATION: test
      AMOUNT: 1
      ENDPOINT: http://cameltest:8080/datalab-example/endpoints/pvreceiver
    depends_on:
      - cameltest
  starter:
    build:
      context: starter
    environment:
      INSTALLATION: test
      AMOUNT: 1
      DELAY: 10
      DURATION: 600
      SENDER: http://camelsender:3000
      ENDPOINT: http://cameltest:8080/datalab-example/endpoints/pvreceiver

volumes:
  camelsender:
    driver: local
  cameltest:
    driver: local
  camelreceiver:
    driver: local
