version: "2"

services:
  receiver:
    build:
      context: receiver
    restart: unless-stopped
    volumes:
      - storage_receiver:/noderedtest:Z
    ports:
      - "1881:1880"
  test:
    build:
      context: wso2
    restart: unless-stopped
    volumes:
      - storage_test:/wso2test:Z
    depends_on:
      - receiver
  sender:
    build:
      context: sender
    restart: unless-stopped
    volumes:
      - storage_sender:/noderedtest:Z
    environment:
      INSTALLATION: test
      AMOUNT: 1
      ENDPOINT: http://test:9763/endpoints/SolarReceiver
    depends_on:
      - test
volumes:
  storage_receiver:
    driver: local
  storage_sender:
    driver: local
  storage_test:
    driver: local