version: "2"

services:
  receiver:
    build:
      context: receiver
    restart: unless-stopped
    volumes:
      - wso2_receiver:/measurements:Z
    ports:
      - "1881:1880"
  test:
    build:
      context: wso2
    restart: unless-stopped
    volumes:
      - wso2_test:/wso2test:Z
    environment:
      MEASUREMENT_DELAY: 60
    depends_on:
      - receiver
  sender:
    build:
      context: sender
    restart: unless-stopped
    volumes:
      - wso2_sender:/measurements:Z
    environment:
      MEASUREMENT_DELAY: 60
      INSTALLATION: test
      AMOUNT: 1
      ENDPOINT: http://test:9763/endpoints/SolarReceiver
    depends_on:
      - test
volumes:
  wso2_receiver:
    driver: local
  wso2_sender:
    driver: local
  wso2_test:
    driver: local
