version: "2"

services:
  nifireceiver:
    build:
      context: receiver
#    Only required for debugging
#    ports:
#      - "1881:1880"
    volumes:
      - nifireceiver:/measurements:rw
  nifitest:
    build:
      context: nifi
    volumes:
      - nifitest:/measurements:rw
    ports:
      - "9990:9990"
      - "8080:8080"
    environment:
      MEASUREMENT_DELAY: 60
    depends_on:
      - nifireceiver
  nifisender:
    build:
      context: sender
    volumes:
      - nifisender:/measurements:rw
    depends_on:
      - nifitest
  starter:
    build:
      context: starter
    environment:
      MEASUREMENT_DELAY: 60
      INSTALLATION: test
      AMOUNT: 1
      DELAY: 60
      DURATION: 600
      SENDER: http://nifisender:3000
      ENDPOINT: http://nifitest:8000/

volumes:
  nifisender:
    driver: local
  nifitest:
    driver: local
  nifireceiver:
    driver: local
