version: "2"

services:
  nifireceiver:
    build:
      context: receiver
    restart: unless-stopped
#    Only required for debugging
#    ports:
#      - "1881:1880"
    volumes:
      - nifireceiver:/measurements:rw
  nifideploy:
    build:
      context: maven
    depends_on:
      - nifitest
  nifitest:
    build:
      context: nifi
    restart: unless-stopped
    volumes:
      - nifitest:/measurements:rw
    ports:
      - "9990:9990"
      - "8080:8080"
    environment:
      MEASUREMENT_DELAY: 60
    depends_on:
      - nifireceiver
  nifisender:
    build:
      context: sender
    restart: unless-stopped
    volumes:
      - nifisender:/measurements:rw
    environment:
      MEASUREMENT_DELAY: 60
      INSTALLATION: test
      AMOUNT: 1
      ENDPOINT: http://cameltest:8080/datalab-example/endpoints/pvreceiver
    depends_on:
      - nifitest

volumes:
  nifisender:
    driver: local
  nifitest:
    driver: local
  nifireceiver:
    driver: local
