version: "2"

services:
  wso2receiver:
    build:
      context: receiver
    restart: unless-stopped
    volumes:
      - wso2receiver:/measurements:Z
    ports:
      - "1881:1880"
  wso2test:
    build:
      context: wso2
    restart: unless-stopped
    volumes:
      - wso2test:/measurements:Z
    environment:
      MEASUREMENT_DELAY: 60
    depends_on:
      - wso2receiver
  wso2sender:
    build:
      context: sender
    restart: unless-stopped
    volumes:
      - wso2sender:/measurements:Z
    environment:
      MEASUREMENT_DELAY: 60
      INSTALLATION: test
      AMOUNT: 1
      ENDPOINT: http://wso2test:9763/endpoints/SolarReceiver
    depends_on:
      - wso2test
volumes:
  wso2receiver:
    driver: local
  wso2sender:
    driver: local
  wso2test:
    driver: local
