version: "2"

services:
  noderedreceiver:
    build:
      context: receiver
    restart: unless-stopped
    volumes:
      - noderedreceiver:/measurements:rw
#    Only required for debugging
#    ports:
#      - "1881:1880"
  noderedtest:
    build:
      context: nodered
    restart: unless-stopped
    volumes:
      - noderedtest:/measurements:rw
    environment:
      MEASUREMENT_DELAY: 60
#    Only required for debugging
#    ports:
#      - "1880:1880"
    depends_on:
      - noderedreceiver
  noderedsender:
    build:
      context: sender
    restart: unless-stopped
    volumes:
      - noderedsender:/measurements:rw
    environment:
      MEASUREMENT_DELAY: 60
      INSTALLATION: test
      AMOUNT: 1
      ENDPOINT: http://noderedtest:1880/endpoints/pvreceiver
    depends_on:
      - noderedtest

volumes:
  noderedsender:
    driver: local
  noderedtest:
    driver: local
  noderedreceiver:
    driver: local
