version: "2"

services:
  receiver:
    build:
      context: receiver
    restart: unless-stopped
    volumes:
      - ./volumes/nodered/received:/noderedtest:rw
    ports:
      - "1881:1880"
  test:
    build:
      context: camel
    restart: unless-stopped
    volumes:
      - ./volumes/camel/data:/camel:rw
    ports:
      - "9990:9990"
      - "8080:8080"
    environment:
      WILDFLY_MANAGEMENT_USER: admin
      WILDFLY_MANAGEMENT_PASSWORD: admin
    depends_on:
      - receiver
  # sender:
  #   build:
  #     context: sender
  #   restart: unless-stopped
  #   volumes:
  #     - ./volumes/nodered/sended:/noderedtest:rw
  #   environment:
  #     INSTALLATION: test
  #     AMOUNT: 1
  #     ENDPOINT: http://test:1880/endpoints/pvreceiver
  #   depends_on:
  #     - test
