version: "2"

services:
  receiver:
    build:
      context: receiver
    restart: unless-stopped
    volumes:
      - ./volumes/camel/received:/noderedtest:rw
  deploy:
    build:
      context: maven
    depends_on:
      - test
  test:
    build:
      context: camel
    restart: unless-stopped
    volumes:
      - ./volumes/camel/data:/cameltest:rw
    ports:
      - "9990:9990"
      - "8080:8080"
    environment:
      WILDFLY_MANAGEMENT_USER: admin
      WILDFLY_MANAGEMENT_PASSWORD: admin
    depends_on:
      - receiver
  sender:
    build:
      context: sender
    restart: unless-stopped
    volumes:
      - ./volumes/camel/sended:/noderedtest:rw
    environment:
      INSTALLATION: test
      AMOUNT: 1
      ENDPOINT: http://test:8080/datalab-example/endpoints/pvreceiver
    depends_on:
      - test
