#!/bin/bash

export DELAY=30 #time in s before test
export DURATION=30 #time in s running the test
export WAIT_FOR_TERMINATION=1000 #delay + duration * 2
export SENDER="$1"
export TESTMASCHINE="$2"

function run {
    export INSTALLATION="$1-$2"
    export AMOUNT=$2
    docker-compose -f $1 up -d --build
    sleep $WAIT_FOR_TERMINATION
    docker-compose -f $1 stop
    ../getdata
    docker-compose -f $1 down
}

# List tests
run nifi.yml 10
#run nodered.yml 10
#run nodered.yml 50
#run nodered.yml 100
run camel.yml 10
