#!/bin/bash

sleep $MEASUREMENT_DELAY && 
while true;
do
    for pid in $(pgrep $1);
    do
        line=$(top -bn1 -p $pid | sed -n 's/^\( *[0-9][0-9]*.*\)/\1/p');
        echo $(date +%s) $line >> /measurements/cpu_$pid.txt;  
    done
    sleep 0.$(printf '%04d' $((10000 - 10#$(date +%4N))));
done
