#!/bin/bash

sleep $MEASUREMENT_DELAY && while true; do line=$(jstat -gc $(jps | grep $1 | sed -n 's/^\( *[0-9][0-9]*\).*/\1/p') | sed -n 2p); echo $(date +%s) $line; sleep 0.$(printf '%04d' $((10000 - 10#$(date +%4N)))); done >> /measurements/mem.txt
