#!/bin/bash

sleep $MEASUREMENT_DELAY && while true; do line=$(/opt/java/bin/jstat -gc $(/opt/java/bin/jps | grep $1 | sed -n 's/^\( *[0-9][0-9]*\).*/\1/p') | sed -n 2p); echo $(date +%s) $line; sleep 1; done >> /measurements/mem.txt
