#!/bin/bash
#~ gnuplot -e "files='$1';symbols='$symbols'; outputfilename='/data/timediffs_$2.pdf'" scripts/plottimedifferences.plt

getLabel()
{
    if [[ $1 = *"nifi"* ]]; then
        echo "ApacheNifi"
    fi
    if [[ $1 = *"camel"* ]]; then
        echo "ApacheCamel"
    fi
    if [[ $1 = *"node"* ]]; then
        echo "NodeRED"
    fi
}

symbols="▲ ◆ ● x + ▽ "
for d in $(find $1 -type d)
do
    if [[ $d == *"tests_nifitest"* ]]
    then
        cpufiles=""
        for f in $(find $d -name "cpu_*" ! -name "*.pdf" | sort)
        do
            cpufiles="$cpufiles${f} "
        done
        join -1 1 -2 1 $cpufiles | awk '{print $1,$2,$3,$4,$5,$6,$7,$8,$9,$10+$22,$11,$12,$13}' > $d/cpu.txt
        
        memfiles=""
        for f in $(find $d -name "mem_*" ! -name "*.pdf" | sort)
        do
            memfiles="$memfiles${f} "
        done
        join -1 1 -2 1 $memfiles | awk '{print $1,$2+$19,$3+$20,$4+$21,$5+$22,$6+$23,$7+$24,$8+$25,$9+$26,$10+$27,$11+$28,$12+$29,$13+$30,$14+$31,$15+$32,$16+$33,$17+$34,$18+$35}' > $d/mem.txt
    fi
done
echo "Created Nifi files"

#~ for d in $(find $1 -type d)
#~ do
    #~ if [[ $d == *"tests_"* ]]
    #~ then
        #~ cpufiles=""
        #~ cpulabels=""
        #~ for f in $(find $d -name "cpu.*" ! -name "*.pdf" | sort)
        #~ do
            #~ cpufiles="$cpufiles${f} "
            #~ cpulabels="$cpulabels$(echo $(basename "${f}" ".txt") | sed -e "s/_//g") "
        #~ done
        #~ if [[ $cpufiles != "" ]]
        #~ then
            #~ gnuplot -e "column=10; \
                        #~ files='$cpufiles'; \
                        #~ labels='$cpulabels'; \
                        #~ symbols='$symbols'; \
                        #~ outputfilename='$d/cpu_plot.pdf'; \
                        #~ lowerx='NaN'; \
                        #~ upperx='NaN'" \
                        #~ /scripts/plotcpu.plt
        #~ fi
        #~ memfiles=""
        #~ memlabels=""
        #~ for f in $(find $d -name "mem*" ! -name "*.pdf" ! -name "memory*" | sort)
        #~ do
            #~ memfiles="$memfiles${f} "
            #~ memlabels="$memlabels$(echo $(basename "${f}" ".txt") | sed -e "s/_//g") "
        #~ done
        #~ if [[ $memfiles != "" ]]
        #~ then
            #~ gnuplot -e "files='$memfiles'; \
                        #~ labels='$memlabels'; \
                        #~ symbols='$symbols'; \
                        #~ outputfilename='$d/mem_plot.pdf'" \
                        #~ /scripts/plotram.plt
        #~ fi
    #~ fi
#~ done


for collectparam in "200" "400" "800"
do
    cpufiles=""
    cpulabels=""
    for f in $(find $1/*$collectparam -name "cpu.*" ! -name "*.pdf" -type f | sort)
    do
        cpufiles="$cpufiles${f} "
        cpulabels="$cpulabels$(getLabel $(basename $(dirname "${f}"))$(basename "${f}" ".txt") | sed -e "s/_//g" | sed -e "s/tests//g" | sed -e "s/test//g") "
    done
    echo $cpufiles
    if [[ $cpufiles != "" ]]
    then
        if [[ $collectparam -lt 300 ]]
        then
            parts="30 250 0 30"
        else
            parts="100 300 0 100"
        fi
        gnuplot -e "column=10; \
                    files='$cpufiles'; \
                    labels='$cpulabels'; \
                    symbols='$symbols'; \
                    outputfilename='$1/cpu_"$collectparam"_plot.pdf'; \
                    middling='20.0'; \
                    parts='$parts'; \
                    xlow=0;xhigh=1200; \
                    setstuff=0" \
                    /scripts/plotcpu_large.plt
    fi
    memfiles=""
    memlabels=""
    for f in $(find $1/*$collectparam -name "memory*" -o -name "mem.*" ! -name "*.pdf" -type f | sort)
    do
        memfiles="$memfiles${f} "
        memlabels="$memlabels$(getLabel $(echo $(basename $(dirname "${f}"))$(basename "${f}" ".txt") | sed -e "s/_//g" | sed -e "s/tests//g" | sed -e "s/test//g")) "
    done
    echo $memfiles
    if [[ $memfiles != "" ]]
    then
        if [[ $collectparam -lt 300 ]]
        then
            parts="1000000 6000000 0 300000 "
        else
            parts="600000 6000000 0 600000"
        fi
        gnuplot -e "column=10; \
                    files='$memfiles'; \
                    labels='$memlabels'; \
                    symbols='$symbols'; \
                    outputfilename='$1/mem_"$collectparam"_plot.pdf'; \
                    middling='20.0'; \
                    parts='$parts'; \
                    xlow=0;xhigh=1200" \
                    /scripts/plotmem_large.plt
    fi
done

#~ respparam=100
#~ for toolparam in "node" "nifi" "camel"
#~ do
    #~ respfiles=""
    #~ resplabels=""
    #~ for f in $(find $1/responses/* -name "*$toolparam*-$respparam" ! -name "*.pdf" -type f | sort)
    #~ do
        #~ respfiles="$respfiles${f} "
        #~ resplabels="$resplabels$(echo $(basename $(dirname "${f}"))$(basename "${f}" ".txt") | sed -e "s/_//g" | sed -e "s/tests//g" | sed -e "s/test//g") "
    #~ done
    #~ echo $respfiles
    #~ if [[ $respfiles != "" ]]
    #~ then
        #~ gnuplot -e "column=10; \
                    #~ files='$respfiles'; \
                    #~ labels='$resplabels'; \
                    #~ symbols='$symbols'; \
                    #~ outputfilename='$1/response_"$respparam$toolparam"_plot.pdf'; \
                    #~ middling='20'; \
                    #~ parts='900 1200'" \
                    #~ /scripts/plottimedifferences.plt
    #~ fi
#~ done

for f in $(find $1/responses -name "logs_*" ! -name "*.pdf" ! -name "*errors*" | sort -t- -k2)
do
    echo "$f"
    echo "Messages : $(cat $f | wc -l)"
    echo "Single -10 : $(grep ' \-10' $f | wc -l)"
    echo "Double -10 : $(grep ' \-10 \-10' $f | wc -l)"
done

num1=$(cat $1/responses/outgoing.json | grep -e 'nodered.yml-800.*error' | wc -l)
num2=$(cat $1/responses/outgoing.json |grep -e 'nodered.yml-800.*error' | grep -e 'ETIMEDOUT' | wc -l)
num3=$(cat $1/responses/outgoing.json |grep -e 'nodered.yml-800.*error' | grep -e 'EADDRNOTAVAIL' | wc -l)
num4=$(cat $1/responses/outgoing.json |grep -e 'nodered.yml-800.*error' | grep -e 'ECONNRESET' | wc -l)
echo "ALL Error NodeRED : $num1 (checked sum : $(( $num2+$num3+$num4 )))"
echo "ETIMEDOUT Error NodeRED : $num2"
echo "EADDRNOTAVAIL Error NodeRED : $num3"
echo "ECONNRESET Error NodeRED : $num4"

for f in $(find $1/responses -name "logs_*" ! -name "*.pdf" ! -name "*errors*" | sort -t- -k2)
do
    echo $f
    echo "$(awk 'BEGIN{count1=0;avg1=0;count2=0;avg2=0}{if($3-$2>0){count1=count1+1;avg1=avg1+($3-$2)}}{if($4-$2>0){count2=count2+1;avg2=avg2+($4-$2)}}END{if(count1>0){print "DB:",avg1/count1};if(count2>0){print "AVG:",avg2/count2};print count1,count2}' $f)"
done

for f in $(find $1 -name "histo*" ! -name "*.pdf" | sort)
do
    gnuplot -e "filename='$f';x0=1;x1=500;x2=500000;y0=10000;y1=20000;y2=100000" /scripts/histoplot.plt
done

#~ #grep 'nifi.*":503' ./responses/outgoing.json | wc -l
